services:
    dnd_dpd_france_shipping.event_listener.shipping_methods_listener:
        class: Dnd\Bundle\DpdFranceShippingBundle\EventListener\ShippingMethodsListener
        arguments:
            - '@dnd_dpd_france_shipping.condition.shippable'
            - '@dnd_dpd_france_shipping.provider.shipping_service'
        tags:
            - { name: kernel.event_listener, event: oro_shipping.applicable_methods, method: enforceDpDFranceValidations }

    dnd_dpd_france_shipping.event_listener.order_listener:
        class: Dnd\Bundle\DpdFranceShippingBundle\EventListener\OrderListener
        arguments:
            - '@dnd_dpd_france_shipping.provider.station_export'
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\OrderBundle\Entity\Order', event: postUpdate }