services:
    dnd_dpd_france_shipping.event_listener.shipping_methods_listener:
        class: Dnd\Bundle\DpdFranceShippingBundle\EventListener\ShippingMethodsListener
        arguments:
            - '@dnd_dpd_france_shipping.condition.shippable'
        tags:
            - { name: kernel.event_listener, event: oro_shipping.applicable_methods, method: enforceDpDFranceValidations }

    dnd_dpd_france_shipping.event_listener.order_listener:
        class: Dnd\Bundle\DpdFranceShippingBundle\EventListener\OrderListener
        arguments:
            - '@monolog.logger.dnd_dpd_france_shipping'
            - '@oro_message_queue.client.message_producer'
            - '@dnd_dpd_france_shipping.provider.settings'
            - '@dnd_dpd_france_shipping.factory.method'
        tags:
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\OrderBundle\Entity\Order', event: postUpdate }