services:
    _defaults:
        tags:
            - { name: oro_message_queue.topic }

    Dnd\Bundle\DpdFranceShippingBundle\Async\Topic\ShipmentExportToDpdStationTopic: ~
    Dnd\Bundle\DpdFranceShippingBundle\Async\Topic\ShipmentExportToDpdStationForcedTopic: ~
