parameters:
    dnd_dpd_france_shipping.admin_view.method_template: 'DpdFranceShippingBundle::method/dpdFranceShippingMethodWithOptions.html.twig'
services:
    dnd_dpd_france_shipping.identifier_generator.method:
        parent: oro_integration.generator.prefixed_identifier_generator
        public: true
        arguments:
            - !php/const Dnd\Bundle\DpdFranceShippingBundle\Integration\DpdFranceChannel::TYPE

    dnd_dpd_france_shipping.factory.method:
        class: Dnd\Bundle\DpdFranceShippingBundle\Method\Factory\DpdFranceShippingMethodFromChannelFactory
        arguments:
            - '@dnd_dpd_france_shipping.identifier_generator.method'
            - '@translator'
            - '@oro_integration.provider.integration_icon'

    dnd_dpd_france_shipping.method.provider:
        class: 'Dnd\Bundle\DpdFranceShippingBundle\Method\DpdFranceShippingMethodProvider'
        arguments:
            - !php/const Dnd\Bundle\DpdFranceShippingBundle\Integration\DpdFranceChannel::TYPE
            - '@oro_entity.doctrine_helper'
            - '@dnd_dpd_france_shipping.factory.method'
        tags:
            - { name: oro_shipping_method_provider }
            - { name: doctrine.orm.entity_listener, entity: 'Oro\Bundle\IntegrationBundle\Entity\Channel', event: postLoad }

    dnd_dpd_france_shipping.event_listener.shipping_method_config_data:
        parent: oro_shipping.admin_view.method_template.listener
        arguments:
            - '%dnd_dpd_france_shipping.admin_view.method_template%'
            - '@dnd_dpd_france_shipping.method.provider'
        tags:
            - { name: kernel.event_listener, event: oro_shipping_method.config_data, method: onGetConfigData }

    #dnd_dpd_france_shipping.remove_integration_listener:
    #    parent: oro_shipping.remove_integration_listener
    #    arguments:
    #        - !php/const  Dnd\Bundle\DpdFranceShippingBundle\Integration\DpdFranceChannel::TYPE
    #        - '@dnd_dpd_france_shipping.identifier_generator.method'
    #        - '@oro_shipping.method.event.dispatcher.method_removal'
    #    tags:
    #        - { name: kernel.event_listener, event: oro_integration.channel_delete, method: onRemove }
    #
    #dnd_dpd_france_shipping.disable_integration_listener:
    #    parent: oro_shipping.disable_integration_listener
    #    arguments:
    #        - !php/const  Dnd\Bundle\DpdFranceShippingBundle\Integration\DpdFranceChannel::TYPE
    #        - '@dnd_dpd_france_shipping.identifier_generator.method'
    #        - '@oro_shipping.method_disable_handler.decorator'
    #    tags:
    #        - { name: kernel.event_listener, event: oro_integration.channel_disable, method: onIntegrationDisable }