styles:
    inputs:
        - 'bundles/dnddpdfranceshipping/default/scss/variables/dnddpd-method-config.scss'
        - 'bundles/dnddpdfranceshipping/default/scss/variables/dnddpd-method-pickup-config.scss'
        - 'bundles/dnddpdfranceshipping/default/scss/variables/dnddpd-method-predict-config.scss'

        - 'bundles/dnddpdfranceshipping/default/scss/components/dnddpd-method-pickup.scss'
        - 'bundles/dnddpdfranceshipping/default/scss/components/dnddpd-method-pickup-modal.scss'
        - 'bundles/dnddpdfranceshipping/default/scss/components/dnddpd-method-predict.scss'

        - 'bundles/dnddpdfranceshipping/default/scss/components/minimal-view-pickup.scss'
        - 'bundles/dnddpdfranceshipping/default/scss/components/minimal-view-predict.scss'
        - 'bundles/dnddpdfranceshipping/default/scss/styles.scss'

    output: 'css/styles.css'
